sudo: required
language: node_js
services:
  - docker

addons:
  chrome: stable

before_install:
  - docker build -t docker-ember -f Dockerfile.dev .
  - npm config set spin false

script:
  - docker run docker-ember npm run test
